links:
  help_page: "http://www.railstutorial.org/help"
  book_page: "http://www.railstutorial.org/book"
  home_page: "http://www.railstutorial.org"
models:
  user: 
    name:
      max_length: 50
    email:
      max_length: 255
      valid_email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
